test:
    name: basic-contract-benchmark
    description: test benchmark
    workers:
      type: local
      number: 2
    rounds:
      - label: recordkeeper
        description: Record Keeper benchmark
        txDuration: 30
        rateControl: 
          type: fixed-load
          opts:
            tps: 10
        workload:
          module: /home/as1001/RP/Ethereum Benchmark/caliper/recordkeeper.js
          arguments:
            assets: 10
            contractId: recordkeeper

